In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.14.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.02511945,  0.00927674, -0.32352424, -0.09316084, -0.02494395,
        -0.14558989,  0.2071513 , -0.6063891 , -0.15826952,  0.16762388]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.10519174, 0.10887287, 0.07805236, 0.09827241, 0.10521019,
        0.09325281, 0.13269529, 0.05882195, 0.09207787, 0.1275525 ]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.372441

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2972 - accuracy: 0.9130
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1416 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1059 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0855 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0757 - accuracy: 0.9764


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0742 - accuracy: 0.9775 - 504ms/epoch - 2ms/step


[0.07416091114282608, 0.9775000214576721]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.90130525e-08, 8.93867913e-09, 7.69363669e-06, 1.40491329e-05,
        1.35659636e-10, 8.02106683e-07, 1.58069209e-13, 9.99930263e-01,
        6.07364029e-07, 4.64911827e-05],
       [3.73551181e-08, 7.24459096e-05, 9.99455273e-01, 3.14222591e-04,
        3.25927028e-16, 1.56885726e-04, 9.29833988e-08, 2.80158145e-12,
        1.11850329e-06, 3.25417263e-11],
       [1.06321409e-06, 9.98925984e-01, 1.41669239e-04, 1.06867665e-05,
        5.07352779e-05, 2.27760720e-05, 1.53600449e-05, 7.37600029e-04,
        9.30725801e-05, 9.74024715e-07],
       [9.99889255e-01, 1.42881984e-09, 2.70246328e-05, 1.94301705e-07,
        1.72492960e-07, 3.04801392e-06, 1.58315470e-05, 2.38655025e-06,
        1.15247749e-08, 6.20654100e-05],
       [7.11810981e-06, 3.80841669e-09, 5.48664757e-05, 5.39316375e-07,
        9.87905622e-01, 9.26625603e-07, 3.28719466e-06, 6.90594534e-05,
        1.47841956e-06, 1.19571127e-02]], dtype=float32)>